name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov doctest-dev

    - name: Run coverage.sh
      run: |
        cd tests
        chmod +x coverage.sh
        ./coverage.sh

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./tests/coverage/kstring_coverage.info